import spacy

trained_nlp = spacy.load("./output/model-last")

# text = 'POLICY NUMBER : HXMP101057 COMMERCIAL GENERAL LIABILITY CG 20 37 0413 THIS ENDORSEMENT CHANGES THE POLICY. PLEASE READ IT CAREFULLY. ADDITIONAL INSURED OWNERS, LESSEES OR CONTRACTORS COMPLETED OPERATIONS This endorsement modifies insurance provided under the following: COMMERCIAL GENERAL LIABILITY COVERAGE PART PRODUCTS/COMPLETED OPERATIONS LIABILITY COVERAGE PART SCHEDULE Name Of Additional Insured Person(s) Or OrQanization(s) Location And Description Of Completed Operations As required by written contract. As required by written contract. Information required to complete this Schedule , if not shown above, will be shown in the Declarations. A. Section II Who Is An Insured is amended to include as an additional insured the person(s) or organization(s) shown in the Schedule , but only with respect to liability for "bodily injury" or "property damage" caused, in whole or in part, by "your work" at the location designated and described in the Schedule of this endorsement performed for that additional insured and included in the "productscompleted operations hazard". However: 1. The insurance afforded to such additional insured only applies to the extent permitted by law; and 2. If coverage provided to the additional insured is required by a contract or agreement , the insurance afforded to such additional insured will not be broader than that which you are required by the contract or agreement to provide for such additional insured. B. With respect to the insurance afforded to these additional insureds, the following is added to Section Ill Limits Of Insurance : If coverage provided to the additional insured is required by a contract or agreement, the most we will pay on behalf of the additional insured is the amount of insurance : 1. Required by the contract or agreement; or 2. Available under the applicable Limits of Insurance shown in the Declarations ; whichever is less. This endorsement shall not increase the applicable Limits of Insurance shown in the Declarations . CG 20 37 0413 ©Insurance Services Office, Inc., 2012 Page 1of1'

# text = 'VE 0184 12 11Policy Number: VOGP001042 VE 0184 12 11Insured Name: ADCO ELECTRICAL CORPNumber: 21 Effective Date: 04/10/2013 THIS ENDORSEMENT CHANGES THE POLICY. PLEASE READ IT CAREFULLY.DESIGNATED CONSTRUCTION PROJECT(S)GENERAL AGGREGATE LIMITThis endorsement modifies insurance provided under the following:Commercial General Liability Coverage PartSCHEDULEDesignated Construction Projects:AS REQUIRED BY WRITTEN CONTRACT(If no entry appears above, information required to complete this endorsement will be shown in the Declarations as applicable to this endorsement.)A.For all sums which the insured becomes legally obligated to pay as damages caused by “occurrences” under COVERAGE A (SECTION I), and for all medical expenses caused by accidents under COVERAGE C (SECTION I), which can be attributed only to ongoing operations at a single designated construction project shown in the Schedule above:1.A separate Designated Construction Project General Aggregate Limit applies to each designated construction project, and that limit is equal to the amount of the General Aggregate Limit shown in the Declarations.However, the most we will pay under the Designated Construction Project General Aggregate Limit for all projects combined is $5,000,000.00.2.The Designated Construction Project General Aggregate Limit is the most we will pay for the sum of all damages under COVERAGE A, except damages because of “bodily injury” or “property damage” included in the “products completed operations hazard”, and for medical expenses under COVERAGE C regardless of the number of:a.Insureds;b.Claims made or “suits” brought; orc.Persons or organizations making claims or bringing “suits”.Page 1 of 2'

# text = 'CG 24 04 10 93 Copyright, Insurance Services Office, Inc., 1992 Page 1 of 1 Policy Number: VOGP001042 CG 24 04 10 93Insured Name: ADCO ELECTRICAL CORPNumber: 24 Effective Date: 04/10/2013 THIS ENDORSEMENT CHANGES THE POLICY. PLEASE READ IT CAREFULLYWAIVER OF TRANSFER OF RIGHTS OF RECOVERYAGAINST OTHERS TO USThis endorsement modifies insurance provided under the following:COMMERCIAL GENERAL LIABILITY COVERAGESCHEDULEName of Person or Organization: AS REQUIRED BY WRITTEN CONTRACT(If no entry appears above, information required to complete this endorsement will be shown in the Declarations as applicable to this endorsement.) The TRANSFER OF RIGHTS OF RECOVERY AGAINST OTHERS TO US Condition (Section IV  COMMERCIAL GENERAL LIABILITY CONDITIONS) is amended by the addition of the following: We waive any right of recovery we may have against the person or organization shown in the Schedule above because of payments we make for injury or damage arising out of your ongoing operations or "your work" done under a contract with that person or organization and included in the "productscompleted operations hazard". This waiver applies only to the person or organization shown in the Schedule above.'

# text = 'CG 24 04 10 93 Copyright, Insurance Services Office, Inc., 1992 Page 1 of 1 Policy Number: VOGP001042 CG 24 04 10 93Insured Name: ADCO ELECTRICAL CORPNumber: 24 Effective Date: 04/10/2013 THIS ENDORSEMENT CHANGES THE POLICY. PLEASE READ IT CAREFULLYWAIVER OF TRANSFER OF RIGHTS OF RECOVERYAGAINST OTHERS TO USThis endorsement modifies insurance provided under the following:COMMERCIAL GENERAL LIABILITY COVERAGESCHEDULEName of Person or Organization: AS REQUIRED BY WRITTEN CONTRACT(If no entry appears above, information required to complete this endorsement will be shown in the Declarations as applicable to this endorsement.) The TRANSFER OF RIGHTS OF RECOVERY AGAINST OTHERS TO US Condition (Section IV  COMMERCIAL GENERAL LIABILITY CONDITIONS) is amended by the addition of the following: We waive any right of recovery we may have against the person or organization shown in the Schedule above because of payments we make for injury or damage arising out of your ongoing operations or "your work" done under a contract with that person or organization and included in the "productscompleted operations hazard". This waiver applies only to the person or organization shown in the Schedule above.'

text = 'cg 24 04 10 93 copyright, insurance services office, inc., 1992 page 1 of 1 policy number: vogp001042 cg 24 04 10 93insured name: adco electrical corpnumber: 24 effective date: 04/10/2013 this endorsement changes the policy. please read it carefullywaiver of transfer of rights of recoveryagainst others to usthis endorsement modifies insurance provided under the following:commercial general liability coverageschedulename of person or organization: as required by written contract(if no entry appears above, information required to complete this endorsement will be shown in the declarations as applicable to this endorsement.) the transfer of rights of recovery against others to us condition (section iv  commercial general liability conditions) is amended by the addition of the following: we waive any right of recovery we may have against the person or organization shown in the schedule above because of payments we make for injury or damage arising out of your ongoing operations or "your work" done under a contract with that person or organization and included in the "productscompleted operations hazard". this waiver applies only to the person or organization shown in the schedule above.'


doc = trained_nlp(text)

for ent in doc.ents:
    # print(ent.text, ent.start_char, ent.end_char, ent.label_)
    print('ent.text: ', ent.text)
    print('label: ', ent.label_)
if len(doc.ents) == 0:
    print ("No entities found.")