import spacy

from training_data_generation import generateTestingDataTextFromPDF

trained_nlp = spacy.load("./output/model-last")

# text = 'POLICY NUMBER : HXMP101057 COMMERCIAL GENERAL LIABILITY CG 20 37 0413 THIS ENDORSEMENT CHANGES THE POLICY. PLEASE READ IT CAREFULLY. ADDITIONAL INSURED OWNERS, LESSEES OR CONTRACTORS COMPLETED OPERATIONS This endorsement modifies insurance provided under the following: COMMERCIAL GENERAL LIABILITY COVERAGE PART PRODUCTS/COMPLETED OPERATIONS LIABILITY COVERAGE PART SCHEDULE Name Of Additional Insured Person(s) Or OrQanization(s) Location And Description Of Completed Operations As required by written contract. As required by written contract. Information required to complete this Schedule , if not shown above, will be shown in the Declarations. A. Section II Who Is An Insured is amended to include as an additional insured the person(s) or organization(s) shown in the Schedule , but only with respect to liability for "bodily injury" or "property damage" caused, in whole or in part, by "your work" at the location designated and described in the Schedule of this endorsement performed for that additional insured and included in the "productscompleted operations hazard". However: 1. The insurance afforded to such additional insured only applies to the extent permitted by law; and 2. If coverage provided to the additional insured is required by a contract or agreement , the insurance afforded to such additional insured will not be broader than that which you are required by the contract or agreement to provide for such additional insured. B. With respect to the insurance afforded to these additional insureds, the following is added to Section Ill Limits Of Insurance : If coverage provided to the additional insured is required by a contract or agreement, the most we will pay on behalf of the additional insured is the amount of insurance : 1. Required by the contract or agreement; or 2. Available under the applicable Limits of Insurance shown in the Declarations ; whichever is less. This endorsement shall not increase the applicable Limits of Insurance shown in the Declarations . CG 20 37 0413 ©Insurance Services Office, Inc., 2012 Page 1of1'

# text = 'VE 0184 12 11Policy Number: VOGP001042 VE 0184 12 11Insured Name: ADCO ELECTRICAL CORPNumber: 21 Effective Date: 04/10/2013 THIS ENDORSEMENT CHANGES THE POLICY. PLEASE READ IT CAREFULLY.DESIGNATED CONSTRUCTION PROJECT(S)GENERAL AGGREGATE LIMITThis endorsement modifies insurance provided under the following:Commercial General Liability Coverage PartSCHEDULEDesignated Construction Projects:AS REQUIRED BY WRITTEN CONTRACT(If no entry appears above, information required to complete this endorsement will be shown in the Declarations as applicable to this endorsement.)A.For all sums which the insured becomes legally obligated to pay as damages caused by “occurrences” under COVERAGE A (SECTION I), and for all medical expenses caused by accidents under COVERAGE C (SECTION I), which can be attributed only to ongoing operations at a single designated construction project shown in the Schedule above:1.A separate Designated Construction Project General Aggregate Limit applies to each designated construction project, and that limit is equal to the amount of the General Aggregate Limit shown in the Declarations.However, the most we will pay under the Designated Construction Project General Aggregate Limit for all projects combined is $5,000,000.00.2.The Designated Construction Project General Aggregate Limit is the most we will pay for the sum of all damages under COVERAGE A, except damages because of “bodily injury” or “property damage” included in the “products completed operations hazard”, and for medical expenses under COVERAGE C regardless of the number of:a.Insureds;b.Claims made or “suits” brought; orc.Persons or organizations making claims or bringing “suits”.Page 1 of 2'

# text = 'CG 24 04 10 93 Copyright, Insurance Services Office, Inc., 1992 Page 1 of 1 Policy Number: VOGP001042 CG 24 04 10 93Insured Name: ADCO ELECTRICAL CORPNumber: 24 Effective Date: 04/10/2013 THIS ENDORSEMENT CHANGES THE POLICY. PLEASE READ IT CAREFULLYWAIVER OF TRANSFER OF RIGHTS OF RECOVERYAGAINST OTHERS TO USThis endorsement modifies insurance provided under the following:COMMERCIAL GENERAL LIABILITY COVERAGESCHEDULEName of Person or Organization: AS REQUIRED BY WRITTEN CONTRACT(If no entry appears above, information required to complete this endorsement will be shown in the Declarations as applicable to this endorsement.) The TRANSFER OF RIGHTS OF RECOVERY AGAINST OTHERS TO US Condition (Section IV  COMMERCIAL GENERAL LIABILITY CONDITIONS) is amended by the addition of the following: We waive any right of recovery we may have against the person or organization shown in the Schedule above because of payments we make for injury or damage arising out of your ongoing operations or "your work" done under a contract with that person or organization and included in the "productscompleted operations hazard". This waiver applies only to the person or organization shown in the Schedule above.'

# text = 'CG 24 04 10 93 Copyright, Insurance Services Office, Inc., 1992 Page 1 of 1 Policy Number: VOGP001042 CG 24 04 10 93Insured Name: ADCO ELECTRICAL CORPNumber: 24 Effective Date: 04/10/2013 THIS ENDORSEMENT CHANGES THE POLICY. PLEASE READ IT CAREFULLYWAIVER OF TRANSFER OF RIGHTS OF RECOVERYAGAINST OTHERS TO USThis endorsement modifies insurance provided under the following:COMMERCIAL GENERAL LIABILITY COVERAGESCHEDULEName of Person or Organization: AS REQUIRED BY WRITTEN CONTRACT(If no entry appears above, information required to complete this endorsement will be shown in the Declarations as applicable to this endorsement.) The TRANSFER OF RIGHTS OF RECOVERY AGAINST OTHERS TO US Condition (Section IV  COMMERCIAL GENERAL LIABILITY CONDITIONS) is amended by the addition of the following: We waive any right of recovery we may have against the person or organization shown in the Schedule above because of payments we make for injury or damage arising out of your ongoing operations or "your work" done under a contract with that person or organization and included in the "productscompleted operations hazard". This waiver applies only to the person or organization shown in the Schedule above.'


# text = 'policy number: 1tpm ny1701234898 commercial general liability cg 20 26 04 13 this endorsement changes the policy. please read it carefully. cg 20 26 04 13 © insurance services office, inc., 2012 page 1 of 1 additional insured  designated person or organization this endorsement modifies insurance provided under the following: commercial general liability coverage part schedule name of additional insured person(s) or organization(s): the city of new york, including its officials and employees ; new york city transit authority ( "nyct"), the manhattan and bronx surface transit operating authority ("mabstoa"), the staten island rapid transit operating authority ("sirtoa"), the metropolitan transportation authority ("mta") including its subsidiaries and affiliates, mta capital construction ("mtacc"), mta bus company ("mta bus"), and the city of new york ("city" as owner) and the representative affiliates and subsidiaries existing currently or in the future of and successors to each indemnified partie s listed herein. information requ ired to complete this schedule, if not shown above, will be shown in the declarations. a. section ii  who is an insured is amended to include as an additional insured the person(s) or organization(s) shown in the schedule, but only with respect to liability for "bodily injury", "property damage" or "personal and advertising injury" caused, in whole or in part, by your acts or omissions or the acts or omissions of those acting on your behalf: 1. in the performance of your ongoing operations; or 2. in connection with your premises owned by or rented to you. however: 1. the insurance afforded to such additional insured only applies to the extent permitted by law; and 2. if coverage provided to the additional insured is required by a contract or agreement, the insurance afforded to such additional insured will not be broader than that which you are required by the contract or agreement to provide for such additional insured b. with respect to the insurance afforded to these additional insureds, the following is added to section iii  limits of insurance: if coverage provided to the additional insured is required by a contract or agreement, the most we will pay on behalf of the additional insured is the amount of insurance: 1. required by the contract or agreement; or 2. available under the applicable limits of insurance shown in the declarations: whichever is less. this endorsement shall not increase the applicable limits of insurance shown in the declarations.'
# text = 'administered by hiscox inc.520 madison avenue 32nd floor, new york, ny 10022(646) 4522353endorsement 22named insured: bedrock plumbing and heating, inc.wclgl e6851 cw (04/16)page 1 of 2glenslren75e6851.1 specific primary and noncontributory endorsement  scheduled contractsin consideration of the premium charged, and on the understanding this endorsement leaves all other terms, conditions, andexclusions unchanged, it is agreed the general liability coverage part is amended as follows:schedulecontract(s)name of additional insured(s)n/astorage construction26 west 17th street, suite 801new york, ny 10011163 6th street llc  project owner; storage deluxe managementcompany, llc property manager; storage construction company,llc general contractor; petros realty corp  ground lessor; andtheir respective owners, managers, principals, employees, agentsand assigns, lender as needed, atima c/o storage deluxe, 26west 17th street, suite 801, new york, ny 10011.444 55th street llc  landlord; uovo management llcproperty manager; cubesmart asset management llc property manager; storage deluxe management company, llcdevelopment manager; storage construction company llc general contractor; and their respective owners, managers,principals, employees, agents and assigns, lender as needed.atima c/o storage deluxe, 26 west 17th street, suite 801, newyork, ny 10011i.section iii. who is an insured, k. additional insureds, is amended to include as an additional insured the person(s) ororganization(s) shown in the schedule above, but only to the extent required in the contract or agreement you entered intonaming such additional insured and identified in the schedule above.ii.notwithstanding anything to the contrary in the other insurance provisions of the general terms and conditions or in thiscoverage part, the coverage available under this coverage part to any additional insured identified in the schedule above willbe primary and noncontributory, and any other insurance available to the additional insured for the same claim or occurrencewill be specifically excess of the coverage part limit.iii.the coverage afforded to the additional insured(s) listed above is subject to all of the terms and conditions of section iii. who isan insured, k. additional insureds.endorsement effective:04/06/2018certificate no.:mpl1925088.18endorsement no:22processed date:03/29/2018hiscox inc.'
# text  = 'policy number: u17pc30098 00 commercial general liability cg 04 35 12 07 this endorsement changes the policy. please read i t carefully. cg 04 35 12 07 © iso properties, inc., 2006 page 1 of 6  class 191585 risk employee benefits liability coverage this endorsement provides claimsmade coverage. please read the entire endorsement carefully. this endorsement modifies insurance provided under the following: commercial general liability coverage part schedule coverage limit of insurance each employee deductible premium employee benefits programs $ 1,000,000 each employee $ 5,000 $ included $ 1,000,000 aggregate retroactive date: 05/01/2010 information required to complete this schedule, if not shown above, will be shown in the declarations. a. the following is added to section i  coverages: coverage  employee benefits liability 1. insuring agreement a. we will pay those sums that the insured becomes legally obligated to pay as dam ages because of any act, error or omission, of the insured, or of any other person for whose acts the insured is legally liable, to which this insurance applies. we will have the right and duty to defend the insured against any "suit" seeking those damages. however, we will have no duty to defend the insured against any "suit" seeking dam ages to which this insurance does not ap ply. we may, at our discretion, investigate any report of an act, error or omission and settle any "claim" or "suit" that may result. but: (1) the amount we will pay for damages is limited as described in paragraph d. (section iii  limits of insurance); and (2) our right and duty to defend ends when we have used up the applicable limit of insurance in the payment of judgments or settlements. no other obligation or liability to pay sums or perform acts or services is covered un less explicitly provided for under supple mentary payments. b. this insurance applies to damages only if: (1) the act, error or omission, is negligently committed in the "administration" of your "employee benefit program"; (2) the act, error or omission, did not take place before the retroactive date, if any, shown in the schedule nor after the end of the policy period; and (3) a "claim" for damages, because of an act, error or omission, is first made against any insured, in accordance with paragraph c. below, during the policy period or an extended reporting period we provide under paragraph f. of this endorsement. c. a "claim" seeking damages will be deemed to have been made at the earlier of the fol lowing times: (1) when notice of such "claim" is received and recorded by any insured or by us, whichever comes first; or ics builders inc policy  u17pc3009800.pdf'


## Testing Texts - Passed
# text = 'policy number: u17pc3009800 commercial general liability cg 20 10 07 04 this endorsement changes the policy. please read i t carefully. cg 20 10 07 04 class 191585 risk © iso properties, inc., 2004 page 1 of 1  additional insured  owners, lessees or contractors  scheduled person or organization this endorsement modifies insurance provided under the following: commercial general liability coverage part schedule name of additional insured person(s) or orga niz ation(s): location(s) of covered operations any person or organization for whom you are perform ing operations during the policy period when you and su ch person or organization have agreed in writing in a contract or agreement that such person or organization be ad ded as an additional insured on your policy. information required to complete this schedule, if not shown above, will be shown in the declarations. a. section ii  who is an insured is amended to include as an additional insured the person(s) or organization(s) shown in the schedule, but only with respect to liability for "bodily injury", "pro perty damage" or "personal and advertising injury" caused, in whole or in part, by: 1. your acts or omissions; or 2. the acts or omissions of those acting on your behalf; in the performance of your ongoing operations for the additional insured(s) at the location(s) designated above. b. with respect to the insurance afforded to these additional insureds, the following additional exclu  sions apply: this insurance does not apply to "bodily injury" or "property damage" occurring after: 1. all work, including materials, parts or equip ment furnished in connection with such work, on the project (other than service, maintenance or repairs) to be performed by or on behalf of the additional insured(s) at the location of the covered operations has been completed; or 2. that portion of "your work" out of which the injury or damage arises has been put to its in tended use by any person or organization other than another contractor or subcontractor en gaged in performing operations for a principal as a part of the same project. ics builders inc policy  u17pc3009800.pdf'
# text = 'policy number: commercial general liability cg 20 10 0413 this endorsement changes the policy. please read it carefully. additional insured owners, lessees or contractors scheduled person or organization this endorsement modifies insurance provided under the following : commercial general liability coverage part schedule name of additional insured person(s) or organization(s) location(s) of covered operations as required by written contract executed prior to the as required by writte n contract executed prior to date of an occurrence. the date of an occurrence. information required to comp lete this schedule , if not shown above , will be shown in the declarations.'
# text = '081417 dtco2h296651til1710,000commerc general labil ial iitypolicy : issued: number atethisendorsement changes thepolicy. please readitcarefully.deductible liability insurance newyorkthisendorsement iiesinsurance proidedundertfol modf v helowing:commerc general lityvera a ial iabil co geprtproducts pleted peraonslitycovera part /com oti abili geschedulecoverage amount uctiofdedbleperoccurrencepropertyda iabity,includ mtedcoerage $ magelli ingliivforpolioncosts(ilicabonly lut fapple),orbodiljurylyandproperty mageliabli $ yinliabiit da ity,includ lmv potioncosts(iapplcable), ingiitedcoerageforllu ficombined(inoentryappearsaboveinmaionrequiredtocomp thendorsement willbeshowninthedeclarations f ,fort leteisasapplicable isendorsement.)tothprovionssiapplicati ofendorse t on men(enterbelowanylmtionsontheapplionothendorsement. ino iita icatfis fliiion ibiesto: mtatisentered,thedeductleappla.damages ll"property da" ll"iitedcveredpolioncosts"(fappcable); fora mageandtoalmo lut iliorb.damages foral"bodiinjur"and"property dage"andtoall"lmtedcopotioncosts"(iappla llyy ma iiveredllu ficble);howevercaused):1. 2. ouroblion: thedeductib mountstated igat lea inthescheduleabo iesasfo veappl llows:a.underthebodiinlland lyjuryiabiitya.underproperty damage liabilycoritve property da liabiitycoeragesto mage lvpaydamages onbehalfotheinsured; age,including liico forpol f mtedverageand lut fappionlytoa: ioncosts(ilcable), ,llb. (1) underthelimtedcoageforpolut damages because of"property dam iver lioncosts(iapplicab topay"lmco age";and f le) iitedveredpollut costs"onbehalfothein ion f(2)"liitedcoeredpolioncosts"(i mv lut fsured;applicable);appliesonlytotheaoda and mountfmagesastheresulto "occurrence"; fanyone or"lmve ioncosts"(ifappl iitedcoredpollut icable)b.underbodilyinjurliabiandproperty yiltyineofanydeduct atstatedin xcess iblemoundamage liabiitycoerage,incd lv luingtheschedule aboasapplicab tosuch ve lecoverages.cgf2491208 ©2008thetravelers companies, inc. page1o2f'



# pdfFile = "src/samples/schedule_text1.pdf"
# pdfFile = "src/samples/schedule_text2.pdf"
# pdfFile = "src/samples/Additional_Insureds_Testing_One.pdf"
# pdfFile = "src/samples/Additional_Insureds_Testing_Two.pdf"
pdfFile = "src/samples/Additional_Insureds_Testing_Three.pdf"


# test the saved model
def testModel(pdfFile):
    texts = generateTestingDataTextFromPDF(pdfFile)
    trained_nlp = spacy.load("./output/model-last")
    
    for text in texts:
        doc = trained_nlp(text)
        for ent in doc.ents:
            print(ent.text, ent.start_char, ent.end_char, ent.label_)
        if len(doc.ents) == 0:
            print ("No entities found.")
         
            
if __name__ == "__main__":
    testModel(pdfFile)






